### ISSUE TITLE
[zabbix-community/zabbix] version 6.0.0 unable to bootstrap its database

### ISSUE THREAD

**Issue by Gazeka74** [zabbix-community/helm-zabbix#122]
**Describe the bug**
Deploying chart from scratch on a new database results in the deployment being stuck, the init container never returns. 
There is no bootstrapping of some sort, where Zabbix populates its database the first time it runs. 

Version of Helm and Kubernetes:
Kubernetes 1.30.3 (Azure AKS) 

**What happened**:

```
** waiting for Zabbix DB to be operational to start Zabbix server container
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
*******************
* DB_SERVER_HOST: REDACTED.postgres.database.azure.com
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: ppd_zabbix
* DB_SERVER_SCHEMA: ppd_zabbix
********************
** DB Version not found yet, assuming DB schema is not yet created
*** Waiting 5 seconds...

```
**What you expected to happen**:

```
** Preparing Zabbix server
** Preparing database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: REDACTED.postgres.database.azure.com
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: ppd_zabbix
* DB_SERVER_SCHEMA: ppd_zabbix
********************
** Database 'ppd_zabbix' already exists. Please be careful with database owner!
** Creating 'ppd_zabbix' schema in PostgreSQL
```

**How to reproduce it** (as minimally and precisely as possible):
Fresh deployment off the chart, on an empty database. 
Also, not using the default schema (public) but rather a custom one. This can be achieved by adding an extra env value (cf #120)

**Anything else we need to know**:
It worked fine on version 5.1.0.
Also, upgrading from 5.1.0 to 6.0.0 works fine.
Finally, it is not related to #120 (https://github.com/zabbix-community/helm-zabbix/issues/120)

**Comment by fibbs** [comment]
Hey @Gazeka74,
thanks for this issue, and for #120 as well. From my point of view and if I understand them completely well, they are very related, as both base themselves on the problem of the Helm Chart not being completely aware of non-default ("public") schemas. Indeed, I haven't paid attention to this fact yet, as mostly I am using databases located inside the Kubernetes cluster, and I use either PGO or CNPG operator to manage these, and both follow the "one database instance, one database" approach so that schema management becomes less important than it might be with external databases.

That said, I have a solution in mind where I would make all the keys of the postgress-access secret configurable, and add one for the DB schema to use, falling back to the behavior we have now if not defined. Of course, it would have to be made consistent that both the post-install/upgrade initialization job (which you apparently didn't use, not enabling Zabbix Server HA) and also the sidecar container waiting for the database to be fully available, would respect that setting.

I am going to work on this within the next days.

**Comment by fibbs** [comment]
I believe I have a running version solving your two issues. I will do some more extensive tests during the next days, currently I have only tested using `helm template` and making sure the output is what I expect it to be in the different situations.

If you want to help testing, check it out [here in my fork of this repository](https://github.com/fibbs/helm-zabbix/tree/sql_schema)

**Comment by remmen-io** [comment]
I'm struggling with version 6.1.1 to create a fresh installation of zabbix

The zabbix-server "init-wait-for-database-schema" pod fails with

```
2024-12-03 14:04:23.380Z init-wait-for-database-schema ** DB Version not found yet, assuming DB schema is not yet created
2024-12-03 14:04:23.380Z init-wait-for-database-schema *** Waiting 5 seconds...
```

I do see the postgres server pod and can connect to it

```
zabbix@zabbix-zabbix-server-56889bb84f-kd5rl:/var/lib/zabbix$ psql -h zabbix-postgresql
Password for user zabbix:
psql (16.4 (Ubuntu 16.4-0ubuntu0.24.04.2), server 16.5 (Debian 16.5-1.pgdg120+1))
Type "help" for help.

zabbix=#
zabbix=# \dt
Did not find any relations.
zabbix=# \dn
      List of schemas
  Name  |       Owner
--------+-------------------
 public | pg_database_owner
(1 row)

zabbix=# \dt
Did not find any relations.
```

I'm using ArgoCD to deploy the helm chart with minimal configuration

```
values: |
        zabbixServerHA:
          enabled: false
```
Did I miss something?
