### ISSUE TITLE
[zabbix-community/zabbix] External Databases

### ISSUE THREAD

**Issue by seanfariacustomink** [zabbix-community/helm-zabbix#21]
Allow Zabbix to connect to external databases (MySQL, PostgreSQL, MariaDB) via "values.yaml" and disable PostgreSQL DB creation.

**Comment by aeciopires** [comment]
This issue is related with #18

**Comment by xeberth** [comment]
Our company is migrating most of its workloads to kubernetes, including zabbix.

In terms of offering a robust HA monitoring service, external database support is business critical. It allows us to connect self-managed AWS RDS databases that offer HA

**Comment by fibbs** [comment]
External databases are fully supported. We just only focus on Postgresql, as none of the maintainers of this Helm Chart have the need to support other DBMS. Especially for HA support, pre-initialization of DB schema, handling major release upgrades etc. there is quite a bit of work to do to support MySQL, and it would be continuous work to do and to verify with every new version of Zabbix. That's why we don't support MySQL / MariaDB with this Helm Chart right now. We are nevertheless open to look as (good, complete) PRs.
